### ISSUE TITLE
Feature Request: Use aurora droid instead of Fdroid

### ISSUE THREAD

**Issue by animeking9901** [omnirom/android_prebuilts_prebuiltapks#14]
Requested apk: Aurora droid
Download link: https://f-droid.org/en/packages/com.aurora.adroid/
Reasoning: Has prebuilt repos,including the official MicroG and NanoDroid repos,in the event they update before a new build occurs. All included repos are OPT-IN
Type of Request: UX

**Comment by maxwen** [comment]
no
